/*
 * Copyright 2025 NEC Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License. You may obtain
 * a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

import { APIUsers } from '@/types';

// dummy data
export const dummyAPIUsers: APIUsers = [
  {
    id: '4ec81240-5dab-4d3c-986f-f3d335e9b70b',
    createdTimestamp: 1677647537546,
    username: 'user01',
    enabled: true,
    totp: false,
    emailVerified: false,
    lastName: 'last',
    firstName: 'first01',
    email: 'user01@test.test',
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 0,
  },
  {
    id: '4ec81240-5dab-4d3c-986f-f3d335e9b70c',
    createdTimestamp: 1677647537546,
    username: 'user02',
    enabled: false,
    totp: false,
    emailVerified: false,
    lastName: 'Kikin',
    firstName: 'Taro',
    email: 'user02@test.test',
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 0,
  },
  {
    id: '4ec81240-5dab-4d3c-986f-f3d335e9b70d',
    createdTimestamp: 1677647537546,
    username: 'user03',
    enabled: true,
    totp: false,
    emailVerified: false,
    firstName: 'first03',
    email: 'user03@test.test',
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 0,
  },
  {
    id: '4ec81240-5dab-4d3c-986f-f3d335e9b70e',
    createdTimestamp: 1677647537546,
    username: 'user04',
    enabled: true,
    totp: false,
    emailVerified: false,
    lastName: 'Kikin',
    email: 'user04@test.test',
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 0,
  },
  {
    id: '4ec81240-5dab-4d3c-986f-f3d335e9b70f',
    createdTimestamp: 1677647537546,
    username: 'user05',
    enabled: true,
    totp: false,
    emailVerified: false,
    lastName: 'last',
    firstName: 'first05',
    email: 'user05@test.test',
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 0,
  },
  {
    id: '4ec81240-5dab-4d3c-986f-f3d335e9b70g',
    createdTimestamp: 1677647537546,
    username: 'user06',
    enabled: true,
    totp: false,
    emailVerified: false,
    lastName: 'last',
    firstName: 'first06',
    email: 'user06@test.test',
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 0,
  },
  {
    id: '4ec81240-5dab-4d3c-986f-f3d335e9b70h',
    createdTimestamp: 1677647537546,
    username: 'user07',
    enabled: true,
    totp: false,
    emailVerified: false,
    lastName: 'Kikin',
    firstName: 'Jiro',
    email: 'user07@test.test',
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 0,
  },
  {
    id: '4ec81240-5dab-4d3c-986f-f3d335e9b70i',
    createdTimestamp: 1677647537546,
    username: 'user08',
    enabled: true,
    totp: false,
    emailVerified: false,
    lastName: 'last',
    firstName: 'first08',
    email: 'user08@test.test',
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 0,
  },
  {
    id: '4ec81240-5dab-4d3c-986f-f3d335e9b70j',
    createdTimestamp: 1677647537546,
    username: 'user09',
    enabled: true,
    totp: false,
    emailVerified: false,
    lastName: 'Kikin',
    firstName: 'Yoshiko',
    email: 'user09@test.test',
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 0,
  },
  {
    id: '4ec81240-5dab-4d3c-986f-f3d335e9b70k',
    createdTimestamp: 1677647537546,
    username: 'user10',
    enabled: true,
    totp: false,
    emailVerified: false,
    lastName: 'last',
    firstName: 'first10',
    email: 'user10@test.test',
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 0,
  },
  {
    id: '4ec81240-5dab-4d3c-986f-f3d335e9b70l',
    createdTimestamp: 1677647537546,
    username: 'user11',
    enabled: true,
    totp: false,
    emailVerified: false,
    lastName: 'InfrastructureDynamic',
    firstName: 'Hanako',
    email: 'user11@test.test',
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 0,
  },
  {
    id: '4ec81240-5dab-4d3c-986f-f3d335e9b70m',
    createdTimestamp: 1677647537546,
    username: 'user12',
    enabled: true,
    totp: false,
    emailVerified: false,
    lastName: 'last',
    firstName: 'first12',
    email: 'user12@test.test',
    disableableCredentialTypes: [],
    requiredActions: [],
    notBefore: 0,
  },
];

// For useUserList
export const dummyUsers = [
  [
    {
      id: 'user-admin01',
      username: 'admin01',
      firstName: 'admin',
      lastName: 'lastname',
      email: 'admin@admin.com',
      emailVerified: false,
      attributes: {
        note: ['string'],
      },
      createdTimestamp: 1706250720391,
      enabled: true,
      totp: false,
      disableableCredentialTypes: [],
      requiredActions: [],
      notBefore: 0,
    },
    {
      id: 'user-test001',
      username: 'test001',
      firstName: 'firstName-test001',
      lastName: 'lastName-test001',
      emailVerified: false,
      createdTimestamp: 1706060023219,
      enabled: false,
      totp: false,
      disableableCredentialTypes: [],
      requiredActions: ['UPDATE_PASSWORD'],
      notBefore: 0,
    },
    {
      id: 'user-user01',
      username: 'user01',
      firstName: 'one',
      lastName: 'user',
      email: 'user01@test.com',
      emailVerified: false,
      createdTimestamp: 1705563732506,
      enabled: true,
      totp: false,
      disableableCredentialTypes: [],
      requiredActions: [],
      notBefore: 0,
    },
    {
      id: 'user-user07',
      username: 'user07',
      firstName: 'First Name 07',
      lastName: 'Last Name 07',
      emailVerified: false,
      createdTimestamp: 1706059916074,
      enabled: true,
      totp: false,
      disableableCredentialTypes: [],
      requiredActions: [],
      notBefore: 0,
    },
  ],
  [
    {
      id: 'user-ope01',
      username: 'ope01',
      emailVerified: false,
      createdTimestamp: 1706250745617,
      enabled: true,
      totp: false,
      disableableCredentialTypes: [],
      requiredActions: [],
      notBefore: 0,
    },
    {
      id: 'user-test001',
      username: 'test001',
      firstName: 'firstName-test001',
      lastName: 'lastName-test001',
      emailVerified: false,
      createdTimestamp: 1706060023219,
      enabled: false,
      totp: false,
      disableableCredentialTypes: [],
      requiredActions: ['UPDATE_PASSWORD'],
      notBefore: 0,
    },
  ],
];

export const parsedUsers = [
  {
    attributes: {
      note: ['string'],
    },
    createdTimestamp: 1706250720391,
    disableableCredentialTypes: [],
    email: 'admin@admin.com',
    emailVerified: false,
    enabled: true,
    firstName: 'admin',
    id: 'user-admin01',
    lastName: 'lastname',
    notBefore: 0,
    requiredActions: [],
    roles: ['cdim-administrator'],
    totp: false,
    username: 'admin01',
  },
  {
    createdTimestamp: 1706060023219,
    disableableCredentialTypes: [],
    emailVerified: false,
    enabled: false,
    firstName: 'firstName-test001',
    id: 'user-test001',
    lastName: 'lastName-test001',
    notBefore: 0,
    requiredActions: ['UPDATE_PASSWORD'],
    roles: ['cdim-administrator', 'cdim-operator'],
    totp: false,
    username: 'test001',
  },
  {
    createdTimestamp: 1705563732506,
    disableableCredentialTypes: [],
    email: 'user01@test.com',
    emailVerified: false,
    enabled: true,
    firstName: 'one',
    id: 'user-user01',
    lastName: 'user',
    notBefore: 0,
    requiredActions: [],
    roles: ['cdim-administrator'],
    totp: false,
    username: 'user01',
  },
  {
    createdTimestamp: 1706059916074,
    disableableCredentialTypes: [],
    emailVerified: false,
    enabled: true,
    firstName: 'First Name 07',
    id: 'user-user07',
    lastName: 'Last Name 07',
    notBefore: 0,
    requiredActions: [],
    roles: ['cdim-administrator'],
    totp: false,
    username: 'user07',
  },
  {
    createdTimestamp: 1706250745617,
    disableableCredentialTypes: [],
    emailVerified: false,
    enabled: true,
    firstName: '',
    id: 'user-ope01',
    lastName: '',
    notBefore: 0,
    requiredActions: [],
    roles: ['cdim-operator'],
    totp: false,
    username: 'ope01',
  },
];
